#!/usr/bin/env python3
"""
Build data/ref_history.js — the 1992-2018 referee-history baseline — from
the MIT-licensed epldata R package (github.com/pssguy/epldata, compiled
from public sources by pssguy; unofficial, frozen at May 2018).

Three tables are used:
  games.rda        game_id, game_date, referee_name  (10,127 matches)
  game_team.rda    team_game_id -> game_id
  player_game.rda  per-player appearances with caution Y/N

From those: each referee's career record (matches, cautions per game,
first/last season) and the league's cautions-per-game trend by season.
The output is a small static JS file committed to the repo — the source
data is frozen, so this script only needs re-running if the aggregation
changes.

Referee names arrive as "A.Taylor"; the app matches them to current
officials by initial + surname, the same key build_refs.py uses.

Requires pyreadr (pip install pyreadr). The .rda files are cached in
data/epldata/ (gitignored).

Usage:
    python3 data/build_ref_history.py
"""

import json
import sys
import urllib.request
from pathlib import Path

try:
    import pyreadr
except ImportError:
    sys.exit("ERROR: pip install pyreadr first")

DATA = Path(__file__).resolve().parent
CACHE = DATA / "epldata"
RAW = "https://raw.githubusercontent.com/pssguy/epldata/master/data/{name}.rda"
TABLES = ["games", "game_team", "player_game"]
MIN_MATCHES = 20  # career records below this are too thin to show


def fetch(name):
    CACHE.mkdir(exist_ok=True)
    path = CACHE / f"{name}.rda"
    if not path.exists():
        url = RAW.format(name=name)
        print(f"fetching {url}")
        req = urllib.request.Request(url, headers={"User-Agent": "pl-bookings-ref-history"})
        with urllib.request.urlopen(req, timeout=120) as r:
            path.write_bytes(r.read())
    return pyreadr.read_r(str(path))[name]


def season_of(ts):
    y = ts.year if ts.month >= 7 else ts.year - 1
    return f"{y}/{str(y + 1)[-2:]}"


def main():
    games = fetch("games")
    game_team = fetch("game_team")
    player_game = fetch("player_game")

    # cautions per game_id
    booked = player_game[player_game["caution"] == "Y"]
    tg_to_game = dict(zip(game_team["team_game_id"].astype(int), game_team["game_id"].astype(int)))
    cautions = {}
    unmatched = 0
    for tg in booked["team_game_id"]:
        gid = tg_to_game.get(int(tg))
        if gid is None:
            unmatched += 1
            continue
        cautions[gid] = cautions.get(gid, 0) + 1
    if unmatched:
        print(f"  ({unmatched} cautions without a game join skipped)")

    refs = {}     # name -> [matches, cautions, first_season, last_season]
    seasons = {}  # season -> [matches, cautions]
    for _, row in games.iterrows():
        name = str(row["referee_name"]).strip()
        gid = int(row["game_id"])
        season = season_of(row["game_date"])
        yc = cautions.get(gid, 0)
        if name and name.lower() != "nan":
            r = refs.setdefault(name, [0, 0, season, season])
            r[0] += 1
            r[1] += yc
            r[2] = min(r[2], season)
            r[3] = max(r[3], season)
        s = seasons.setdefault(season, [0, 0])
        s[0] += 1
        s[1] += yc

    season_rows = [
        {"s": s, "ypg": round(c / m, 2), "g": m}
        for s, (m, c) in sorted(seasons.items())
    ]
    ref_rows = sorted(
        (
            {"n": n, "matches": m, "ypg": round(c / m, 2), "first": f, "last": l}
            for n, (m, c, f, l) in refs.items()
            if m >= MIN_MATCHES
        ),
        key=lambda r: -r["ypg"],
    )

    if len(season_rows) < 20 or len(ref_rows) < 40:
        sys.exit(f"ERROR: got {len(season_rows)} seasons / {len(ref_rows)} refs — "
                 "source looks incomplete, refusing to write.")

    out = DATA / "ref_history.js"
    out.write_text(
        "// Auto-generated by build_ref_history.py from the MIT-licensed epldata\n"
        "// R package (github.com/pssguy/epldata) — unofficial data compiled from\n"
        "// public sources, frozen at May 2018. Cautions (yellows) only.\n"
        f"const REF_HISTORY = {{\n"
        f"  span: \"{season_rows[0]['s']}–{season_rows[-1]['s']}\",\n"
        f"  seasons: {json.dumps(season_rows, separators=(',', ':'))},\n"
        f"  refs: {json.dumps(ref_rows, separators=(',', ':'))}\n"
        f"}};\n",
        encoding="utf-8",
    )
    print(f"wrote {out.name}: {len(season_rows)} seasons, {len(ref_rows)} referees "
          f"(of {len(refs)} seen; floor {MIN_MATCHES} matches)")


if __name__ == "__main__":
    main()
