#!/usr/bin/env python3
"""The Champions League ties this app can actually price.

  python3 data/harvest_ucl.py --season 2026

WHAT THIS IS FOR. A European tie is priceable here only when BOTH clubs are
ones a desk already holds players for. `docs/champions-league-feasibility.md`
§1 states the rule and why it is not negotiable:

    BOTH SIDES OR NEITHER - the match total is the sum of the two halves, and
    pricing one off its real XI and the other off last season's minutes would
    make them answer different questions.

With the Premier League, La Liga and Serie A desks built, that is no longer a
rare case. UEFA does not pair two clubs from the same country in the league
phase, so every qualifying tie is one country against another, and the desk
holds three of them.

WHAT IT WRITES. data/ucl_ties.js, one row per tie where both clubs resolve,
each row carrying BOTH clubs' short codes AND the desk each belongs to,
because the two sides come from different datasets and the page has to know
which file to read each from. A tie with one side unheld is dropped, not
half-built.

WHAT IT COSTS. One /fixtures call for the whole competition, once a day. The
squads are already harvested for the domestic desks; nothing here buys a
player.

WHAT IT DELIBERATELY DOES NOT DO.

  * NO REFEREE RATE. A referee's card rate is competition-specific, and the
    desks hold domestic records. Michael Oliver's Premier League rate is not
    his Champions League rate: different instructions, different tempo, and
    cards-per-foul is precisely the quantity that moves. The official's NAME
    is carried so a card can say who it is; his rate is not, and the page
    prices these ties at a neutral referee until a European record exists.
    See §4 of the feasibility note.

  * NO SUSPENSION LADDER. UEFA runs its own accumulation rules and this
    repository does not encode a rung it has not evidenced. The registry is
    untouched.

  * NO NEW CLUBS. Ties involving a club no desk holds are counted in the
    summary and dropped from the file, which is the honest version of what
    this app can and cannot say.
"""

import argparse
import json
import sys
from pathlib import Path

DATA = Path(__file__).resolve().parent
sys.path.insert(0, str(DATA))
import harvest_apifootball as af  # noqa: E402

# The competition, and the desks a club may belong to. Order matters only for
# reporting: a club cannot be in two of these at once.
UCL_LEAGUE_ID = 2
DESKS = ["PL", "LL", "SA"]
OUT = "ucl_ties.js"
CONST = "UCL_TIES"


def desk_of(name):
    """(desk code, club short) for a club a desk holds, or (None, None).

    Asks each desk's own resolver, which is the same call the domestic
    harvests make, so a club is recognised here exactly when its desk would
    recognise it and never by a second spelling table.
    """
    for code in DESKS:
        short = af.short_in(code, name)
        if short:
            return code, short
    return None, None


def map_tie(entry):
    """One /fixtures row as a tie row, or None with the reason.

    Returns (row, unheld) where `unheld` is the list of club names this app
    holds no players for. A row is only produced when that list is empty.
    """
    fx = (entry or {}).get("fixture") or {}
    tm = (entry or {}).get("teams") or {}
    lg = (entry or {}).get("league") or {}
    hn = ((tm.get("home") or {}).get("name") or "").strip()
    an = ((tm.get("away") or {}).get("name") or "").strip()
    if not hn or not an or not fx.get("date"):
        return None, []
    hl, h = desk_of(hn)
    al, a = desk_of(an)
    unheld = [n for n, got in ((hn, h), (an, a)) if not got]
    if unheld:
        return None, unheld
    ref = (fx.get("referee") or "").strip() or None
    if ref:
        # API-Football appends the country: "Michael Oliver, England".
        ref = ref.split(",")[0].strip() or None
    return {
        "id": fx.get("id"),
        "d": fx.get("date"),
        # The round as published ("League Stage - 3"), kept whole. A European
        # season is a league phase and then knockout rounds with names rather
        # than numbers, so a bare integer would lose which is which.
        "r": (lg.get("round") or "").strip() or None,
        "h": h, "hl": hl, "a": a, "al": al,
        "ref": ref,
        "st": ((fx.get("status") or {}).get("short") or "NS"),
    }, []


def emit(rows, season, seen, unheld_names):
    withref = sum(1 for r in rows if r["ref"])
    pairs = sorted({(r["hl"], r["al"]) for r in rows})
    lines = [
        "// Auto-generated by data/harvest_ucl.py. Do not edit by hand.",
        f"// UEFA Champions League {season}-{int(season) % 100 + 1}: {len(rows)} of "
        f"{seen} ties have BOTH clubs on a desk this app holds",
        f"// ({', '.join(a + ' v ' + b for a, b in pairs) or 'none'}); "
        f"{withref} with an official named.",
        "// Player rates are each club's DOMESTIC season, which is what the card",
        "// says: eight European matches is not a sample. No referee rate and no",
        "// suspension ladder - see docs/champions-league-feasibility.md.",
        f"const {CONST} = [",
    ]
    for r in sorted(rows, key=lambda x: str(x["d"])):
        lines.append("  {" + ",".join([
            f'id:{json.dumps(r["id"])}', f'd:{json.dumps(r["d"])}',
            f'r:{json.dumps(r["r"])}',
            f'h:{json.dumps(r["h"])}', f'hl:{json.dumps(r["hl"])}',
            f'a:{json.dumps(r["a"])}', f'al:{json.dumps(r["al"])}',
            f'ref:{json.dumps(r["ref"], ensure_ascii=False)}',
            f'st:{json.dumps(r["st"])}',
        ]) + "},")
    lines.append("];")
    (DATA / OUT).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\n{OUT} written ({len(rows)} priceable of {seen} ties, "
          f"{withref} with an official named)")
    for r in sorted(rows, key=lambda x: str(x["d"])):
        print(f"  {str(r['d'])[:10]}  {r['r'] or '?':<18} "
              f"{r['h']} ({r['hl']}) v {r['a']} ({r['al']})"
              + (f"  ref {r['ref']}" if r["ref"] else ""))
    if unheld_names:
        top = sorted(unheld_names.items(), key=lambda kv: -kv[1])
        print(f"\n  {len(top)} club(s) no desk holds, so their ties are not priced:")
        print("   " + ", ".join(f"{n} x{c}" for n, c in top[:24]))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--season", help="season START year, e.g. 2026 for 2026-27")
    args = ap.parse_args()

    key = af.env_or("API_FOOTBALL_KEY", "")
    if not key:
        sys.exit("ERROR: API_FOOTBALL_KEY is not set.")
    season = args.season or af.env_or("API_FOOTBALL_SEASON", "2026")
    host = af.HOST

    print(f"UEFA Champions League: API-Football league {UCL_LEAGUE_ID}, season {season}")
    payload = af._get(host, key, "fixtures",
                      {"league": UCL_LEAGUE_ID, "season": season})
    errs = af.api_errors(payload)
    if errs:
        sys.exit(f"ERROR: the feed refused the request: {errs}")
    entries = (payload or {}).get("response") or []
    if not entries:
        sys.exit(f"ERROR: no fixtures came back for league {UCL_LEAGUE_ID} "
                 f"season {season}. Refusing to write an empty file over a "
                 "good one.")

    rows, unheld_names = [], {}
    for e in entries:
        row, unheld = map_tie(e)
        if row:
            rows.append(row)
        for n in unheld:
            unheld_names[n] = unheld_names.get(n, 0) + 1

    emit(rows, season, len(entries), unheld_names)
    af.report_usage()
    return 0


if __name__ == "__main__":
    sys.exit(main())
